import type { Metadata } from "next";
import "./globals.css";
import React from "react";

interface IRootLayout {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Devesh Kumar", url: "https://dilicalflame.me" }],
};

export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
